version: '3.8'

services:

  api:
    build: . 
    container_name: my-fastapi-app
    ports:
      - "5000:5000" 

    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis


  redis:
    image: 'redis:latest' 
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: